services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.4
    container_name: keycloak
    env_file:
      - .env    
    command:
      # - start-dev
      - start
      - --hostname=localhost 
      - --hostname-strict=false 
      - --https-certificate-file=/opt/keycloak/certs/keycloak.crt 
      - --https-certificate-key-file=/opt/keycloak/certs/keycloak.key 
      - --https-port=8443 
      - --http-enabled=false 
    depends_on:
      - keycloak-db
    #dev only
    ports:
      #- "8085:8080"
      - "8085:8443"
    networks:
      - archium-network
    # labels:
    #   - "traefik.enable=true"
    volumes:
      - ./exports/realm-export.json:/opt/keycloak/data/import/realm-export.json
      - ./certs:/opt/keycloak/certs

  keycloak-db:
    image: postgres:15.2
    container_name: keycloak-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${KEYCLOAK_DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_POSTGRES_PASSWORD}
      POSTGRES_DB: ${KEYCLOAK_DB_POSTGRES_DB}
    #dev only
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/keycloak_db_data:/var/lib/postgresql/data
    networks:
      - archium-network

  auth-db:
    image: postgres:15.2
    container_name: auth-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${AUTH_DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_POSTGRES_PASSWORD}
      POSTGRES_DB: ${AUTH_DB_POSTGRES_DB}
    #dev only
    ports:
      - "5433:5432"
    volumes:
      - ./volumes/auth_db_data:/var/lib/postgresql/data
    networks:
      - archium-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AUTH_DB_POSTGRES_USER:-postgres} -d ${AUTH_DB_POSTGRES_DB:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  auth-api:
    container_name: auth-api
    build:
      context: .
      dockerfile: src/API/Dockerfile
    env_file:
      - .env
    depends_on:
      keycloak:
        condition: service_started
      auth-db:
        condition: service_healthy
    #dev only
    ports:
      - "5032:80"
    networks:
      - archium-network
    volumes:
      - ../error-codes/errors.json:/app/errors.json:ro
      - ./certs/keycloak.crt:/usr/local/share/ca-certificates/keycloak.crt:ro
    # labels:
    #   - "traefik.enable=true"

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   env_file:
  #     - .env
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - auth-db
  #   networks:
  #     - archium-network
  #   volumes:
  #     - ./volumes/pgadmin_data:/var/lib/pgadmin
  #   labels:
  #     - "traefik.enable=true"

  # kafka1:
  #   image: confluentinc/cp-kafka:7.5.0
  #   container_name: kafka1
  #   ports:
  #     - "9092:9092"
  #     - "19092:19092"
  #   environment:
  #     KAFKA_NODE_ID: 1
  #     KAFKA_PROCESS_ROLES: "broker,controller"
  #     KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:29093,2@kafka2:29093"
  #     KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  #     KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,DOCKER://0.0.0.0:19092,CONTROLLER://0.0.0.0:29093"
  #     KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092,DOCKER://kafka1:19092"
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,DOCKER:PLAINTEXT,CONTROLLER:PLAINTEXT"
  #     KAFKA_INTER_BROKER_LISTENER_NAME: "DOCKER"
  #     KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
  #     KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
  #     KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
  #     KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
  #     KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
  #     KAFKA_DEFAULT_REPLICATION_FACTOR: 2
  #     KAFKA_MIN_INSYNC_REPLICAS: 2
  #     CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
  #   networks:
  #     - archium-network
  #   healthcheck:
  #     test:
  #       [
  #         "CMD",
  #         "kafka-topics",
  #         "--bootstrap-server",
  #         "localhost:9092",
  #         "--list",
  #       ]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #     start_period: 30s
  #   volumes:
  #     - kafka1-data:/var/lib/kafka/data

  # kafka2:
  #   image: confluentinc/cp-kafka:7.5.0
  #   container_name: kafka2
  #   ports:
  #     - "9093:9092"
  #     - "19093:19093"
  #   environment:
  #     KAFKA_NODE_ID: 2
  #     KAFKA_PROCESS_ROLES: "broker,controller"
  #     KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:29093,2@kafka2:29093"
  #     KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  #     KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,DOCKER://0.0.0.0:19092,CONTROLLER://0.0.0.0:29093"
  #     KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9093,DOCKER://kafka2:19092"
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,DOCKER:PLAINTEXT,CONTROLLER:PLAINTEXT"
  #     KAFKA_INTER_BROKER_LISTENER_NAME: "DOCKER"
  #     KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
  #     KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
  #     KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
  #     KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
  #     KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
  #     KAFKA_DEFAULT_REPLICATION_FACTOR: 2
  #     KAFKA_MIN_INSYNC_REPLICAS: 2
  #     CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
  #   networks:
  #     - archium-network
  #   healthcheck:
  #     test:
  #       [
  #         "CMD",
  #         "kafka-topics",
  #         "--bootstrap-server",
  #         "localhost:9092",
  #         "--list",
  #       ]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #     start_period: 30s
  #   volumes:
  #     - kafka2-data:/var/lib/kafka/data
      
  # kafka-ui:
  #   image: provectuslabs/kafka-ui:latest
  #   container_name: kafka-ui
  #   ports:
  #     - "8081:8080"
  #   environment:
  #     - KAFKA_CLUSTERS_0_NAME=local
  #     - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka1:19092,kafka2:19092
  #     - SERVER_PORT=8080
  #   depends_on:
  #     - kafka1
  #     - kafka2
  #   networks:
  #     - archium-network
  #   restart: always 

# volumes:    
#     kafka1-data:
#     kafka2-data:

networks:
  archium-network:
    driver: bridge
    name: archium-network

